# Generated by Django 5.2.4 on 2025-07-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myevent', '0002_usermodel_address_alter_usermodel_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='decorations/')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
